### ISSUE TITLE
Missing data file: `../data/training_pm_nosat.dat`

### ISSUE THREAD

**Issue by ASamarkRoth** [geirtul/event_classification_example#1]
In file `data_import_exploration_traces.ipynb` we want to read the data file `../data/training_pm_nosat.dat` but it is currently missing. 

There are two other files though: 
* CeBr10k_1.txt 
* CeBr200k_Mix.txt.gz

**Comment by OceanNuclear** [comment]
The simplest solution seems to be to upload a link to Zenodo/GoogleDrive/Pastebin/, which includes a truncated version of training_pm_nosat.dat.
Would it be possible to upload that before the weekend? I want to give it a go.

**Comment by geirtul** [comment]
I've updated a zipped file containing 150k traces now, and updated the filename in the notebook.
I'll try to upload the full dataset once I'm on Wi-Fi again.
